version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: |
        docker build -t deloittedigitalapac/drupal-builder -t deloittedigitalapac/drupal-builder:latest .
        docker build --build-arg NODE_VERSION=8.11 -t deloittedigitalapac/drupal-builder:node-8.11 .

     - run: docker push deloittedigitalapac/drupal-builder
